### ISSUE TITLE
Unexpected card drop from player AI

### ISSUE THREAD

**Issue by lifegpc** [donle/sgs#214]
服务器错误
```
D:\sgs\src\server\build\core\player\player.js:281
                throw new Error(`Unexpected card drop from player ${this.Name}`);
                      ^

Error: Unexpected card drop from player AI
    at SmartPlayer.dropCards (D:\sgs\src\server\build\core\player\player.js:281:23)
    at PveGameProcessor.moveCardInGameboard (D:\sgs\src\server\build\core\game\game_processor\game_processor.standard.js:1272:22)
    at D:\sgs\src\server\build\core\game\game_processor\game_processor.standard.js:1184:32
    at PveGameProcessor.StandardGameProcessor.iterateEachStage (D:\sgs\src\server\build\core\game\game_processor\game_processor.standard.js:64:27)
    at async PveGameProcessor.onHandleMoveCardEvent (D:\sgs\src\server\build\core\game\game_processor\game_processor.standard.js:1171:16)
    at async PveGameProcessor.onHandleIncomingEvent (D:\sgs\src\server\build\core\game\game_processor\game_processor.standard.js:727:17)
    at async ServerRoom.moveCards (D:\sgs\src\server\build\core\room\room.server.js:1245:9)
    at async WrappedSkillConstructor.onEffect (D:\sgs\src\server\build\core\skills\game_mode\pve\pve_chaiyue.js:39:13)
    at async D:\sgs\src\server\build\core\game\game_processor\game_processor.standard.js:1020:17
    at async PveGameProcessor.StandardGameProcessor.iterateEachStage (D:\sgs\src\server\build\core\game\game_processor\game_processor.standard.js:64:21)
```

**Comment by Gaeric** [comment]
能提供bug时桌面的截图吗？ 我们需要了解一下当时玩家和AI的手牌状态已便于快速确认问题

**Comment by lifegpc** [comment]
没截图，当时就是玩家手牌有50多张，AI就几张

**Comment by donle** [comment]
和一些虚拟牌的弃置处理有点关系，目前这个问题有点不稳定
